force_multiline_blocks = true
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "preserve"
match_block_trailing_comma = true
tab_spaces = 2